### ISSUE TITLE
Error while trying to list items

### ISSUE THREAD

**Issue by dhondta** [dhondta/rpl-attacks#21]
```
user@instant-contiki:rpl-attacks>> list campaigns
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    FrameworkConsole(parallel=True).cmdloop()
  File "/home/user/rpl-attacks/core/console.py", line 169, in cmdloop
    super(FrameworkConsole, self).cmdloop()
  File "/home/user/rpl-attacks/core/console.py", line 49, in cmdloop
    super(Console, self).cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/user/rpl-attacks/core/utils/decorators.py", line 156, in wrapper
    kwargs['path']).run(*args, **kwargs)
KeyError: 'path'
```

**Comment by dhondta** [comment]
This bug was introduced by commit [89eef0f79cede6a2065347e3a6c88818aaae032e](https://github.com/dhondta/rpl-attacks/commit/89eef0f79cede6a2065347e3a6c88818aaae032e).
