### ISSUE TITLE
Error while loading Fabric

### ISSUE THREAD

**Issue by dhondta** [dhondta/rpl-attacks#39]
```
Traceback (most recent call last):
  File "/usr/local/bin/fab", line 11, in <module>
    load_entry_point('Fabric3==1.14.post1', 'console_scripts', 'fab')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2353, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'
```

This is when I run : `fab setup`, I resolved all the dependencies issue before  and reach at this stage.

**Comment by dhondta** [comment]
**Problem**: As the traceback shows, the error occurs in the early stage of running Fabric, while trying to load the entry point. This may indicate that you have a problem with the version of this package.

**Similar Issue**: Pip [#5599](https://github.com/pypa/pip/issues/5599)

**Solution**: (to be tried) `pip install --upgrade --force-reinstall fabric3`

Please tell me if it fixed the issue.

**Comment by Avani8** [comment]
yes.. pip install --upgrade --force-reinstall fabric3  has fixed the issue. thanks
