### ISSUE TITLE
vagrant up prompts an error

### ISSUE THREAD

**Issue by signif** [dhondta/rpl-attacks#52]
```
Traceback (most recent call last):
	2: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/bin/vagrant:88:in `<main>'
	1: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- vagrant (LoadError)
	20: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/bin/vagrant:88:in `<main>'
	19: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	18: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	17: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	16: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant.rb:40:in `<top (required)>'
	15: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/plugin/manager.rb:4:in `<top (required)>'
	12: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/plugin/manager.rb:4:in `require_relative'
	11: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/bundler.rb:8:in `<top (required)>'
	10: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/package.rb:44:in `<top (required)>'
	 7: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/security.rb:12:in `<top (required)>'
	 4: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /opt/vagrant/embedded/lib/ruby/2.6.0/openssl.rb:13:in `<top (required)>'
	 1: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /opt/vagrant/embedded/lib/libcrypto.so.1.1) - /opt/vagrant/embedded/lib/ruby/2.6.0/i686-linux/openssl.so (LoadError)
```

**Comment by dhondta** [comment]
Hi @signif 
I don't know if you solved your problem since then, but it seems to be a problem of requirement for Vagrant, not the framework. Please check that you installed Vagrant correctly.
