### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by flsubaei** [dhondta/rpl-attacks#7]
I'm running it on Ubuntu 16.04 with contiki 3.0 (not a contiki instant) and python 3.5.2

~~~~{.console}
parallels@ubuntu:~/rpl-attacks$ fab test
2017-02-01 13:22:57 root[3073] INFO Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
2017-02-01 13:22:57 root[3073] INFO Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
2017-02-01 13:22:58 rpla[3073] INFO TESTING THE FRAMEWORK
[localhost] local: python -m unittest tests
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "tests/__init__.py", line 1, in <module>
    from .setup import Test1Config, Test2CoojaSetup
  File "tests/setup.py", line 3, in <module>
    import sh
ImportError: No module named sh

Warning: local() encountered an error (return code 1) while executing 'python -m unittest tests'


Done.
~~~~
----------------------------------------------------------------------------
~~~~{.console}
parallels@ubuntu:~/rpl-attacks$ sudo fab console
2017-02-01 13:31:35 root[4757] INFO Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
2017-02-01 13:31:35 root[4757] INFO Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
[localhost] local: python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from core.console import FrameworkConsole
  File "/home/parallels/rpl-attacks/core/console.py", line 6, in <module>
    from funcsigs import signature
ImportError: No module named funcsigs

Fatal error: local() encountered an error (return code 1) while executing 'python main.py'

Aborting.
parallels@ubuntu:~/rpl-attacks$ sudo pip3 install funcsigs

The directory '/home/parallels/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/parallels/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: funcsigs in /usr/local/lib/python3.5/dist-packages
~~~~

**Comment by flsubaei** [comment]
solved it
the python version was the issue
I think we have to use python 2.7 because fabric does not support 3.5

**Comment by dhondta** [comment]
From [flsubaei](https://github.com/flsubaei) :

I'm running it on Ubuntu 16.04 with contiki 3.0 (not a contiki instant) and python 3.5.2

~~~~{.console}
parallels@ubuntu:~/rpl-attacks$ fab test
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/fabric/main.py", line 672, in main
docstring, callables, default = load_fabfile(fabfile)
File "/usr/local/lib/python3.5/dist-packages/fabric/main.py", line 173, in load_fabfile
imported = importer(os.path.splitext(fabfile)[0])
File "/home/parallels/rpl-attacks/fabfile.py", line 5, in
from core.commands import get_commands
File "/home/parallels/rpl-attacks/core/commands.py", line 19, in
from core.utils.parser import parsing_chain
File "/home/parallels/rpl-attacks/core/utils/parser.py", line 120
except AttributeError:
^
TabError: inconsistent use of tabs and spaces in indentation
~~~~

**Comment by dhondta** [comment]
Thank you very much for signalling this bug ; you spotted a junk tabulation bug !
Now fixed.
